FROM redmine:2.6.10-passenger
MAINTAINER ma1979

RUN apt-get update

# redmine_persist_wfmt の native ext 用
RUN apt-get install -y gcc make pkg-config imagemagick libmagickcore-dev libmagickwand-dev libsqlite3-dev
RUN gem install json -v 1.8.3
RUN gem install rmagick -v 2.13.4
RUN gem install sqlite3 -v 1.3.11

# redmine_persist_wfmt のインストール
RUN git clone https://github.com/pinzolo/redmine_persist_wfmt.git plugins/redmine_persist_wfmt
RUN echo "bundle install --without test development" >> /docker-entrypoint.sh
RUN echo "bundle exec rake redmine:plugins:migrate NAME=redmine_persist_wfmt RAILS_ENV=production" >> /docker-entrypoint.sh
RUN echo "bundle exec rake pwfmt:persist_all FORMAT=textile RAILS_ENV=production" >> /docker-entrypoint.sh
RUN sed -i -e 's/exec "$@"//g' /docker-entrypoint.sh
RUN echo 'exec "$@"' >> /docker-entrypoint.sh